services:
  app:
    build: .
    container_name: sage_app
    volumes:
      - ./:/app
      - ./serviceAccount.json:/app/serviceAccount.json:ro
    ports:
      - "8000:8000"
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/app/serviceAccount.json
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - RABBITMQ_HOST=rabbitmq
    depends_on:
      - redis
      - rabbitmq
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]

  redis:
    image: redis/redis-stack:latest
    container_name: sage_redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

  rabbitmq:
    image: rabbitmq:3-management
    container_name: sage_rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"

volumes:
  redis-data: